// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by sidekick. DO NOT EDIT.

impl std::convert::From<crate::model::AggregationResult> for AggregationResult {
    fn from(value: crate::model::AggregationResult) -> Self {
        Self {
            aggregate_fields: value.aggregate_fields.into_iter().map(|(k, v)| (k.into(), v.into())).collect(),
        }
    }
}

impl std::convert::From<AggregationResult> for crate::model::AggregationResult {
    fn from(value: AggregationResult) -> Self {
        Self::new()
            .set_aggregate_fields(value.aggregate_fields)
    }
}

impl std::convert::From<crate::model::BitSequence> for BitSequence {
    fn from(value: crate::model::BitSequence) -> Self {
        Self {
            bitmap: value.bitmap.into(),
            padding: value.padding.into(),
        }
    }
}

impl std::convert::From<BitSequence> for crate::model::BitSequence {
    fn from(value: BitSequence) -> Self {
        Self::new()
            .set_bitmap(value.bitmap)
            .set_padding(value.padding)
    }
}

impl std::convert::From<crate::model::BloomFilter> for BloomFilter {
    fn from(value: crate::model::BloomFilter) -> Self {
        Self {
            bits: value.bits.map(|v| v.into()),
            hash_count: value.hash_count.into(),
        }
    }
}

impl std::convert::From<BloomFilter> for crate::model::BloomFilter {
    fn from(value: BloomFilter) -> Self {
        Self::new()
            .set_bits(value.bits.map(|v| v.into()))
            .set_hash_count(value.hash_count)
    }
}

impl std::convert::From<crate::model::DocumentMask> for DocumentMask {
    fn from(value: crate::model::DocumentMask) -> Self {
        Self {
            field_paths: value.field_paths.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<DocumentMask> for crate::model::DocumentMask {
    fn from(value: DocumentMask) -> Self {
        Self::new()
            .set_field_paths(value.field_paths)
    }
}

impl std::convert::From<crate::model::precondition::ConditionType> for precondition::ConditionType {
    fn from(value: crate::model::precondition::ConditionType) -> Self {
        use crate::model::precondition::ConditionType as V;
        match value {
            V::Exists(v) => Self::Exists(v.into()),
            V::UpdateTime(v) => Self::UpdateTime((*v).into()),
        }
    }
}

impl std::convert::From<precondition::ConditionType> for crate::model::precondition::ConditionType {
    fn from(value: precondition::ConditionType) -> Self {
        use precondition::ConditionType as V;
        match value {
            V::Exists(v) => Self::Exists(v.into()),
            V::UpdateTime(v) => Self::UpdateTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::Precondition> for Precondition {
    fn from(value: crate::model::Precondition) -> Self {
        Self {
            condition_type: value.condition_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<Precondition> for crate::model::Precondition {
    fn from(value: Precondition) -> Self {
        Self::new()
            .set_condition_type(value.condition_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::transaction_options::ReadWrite> for transaction_options::ReadWrite {
    fn from(value: crate::model::transaction_options::ReadWrite) -> Self {
        Self {
            retry_transaction: value.retry_transaction.into(),
        }
    }
}

impl std::convert::From<transaction_options::ReadWrite> for crate::model::transaction_options::ReadWrite {
    fn from(value: transaction_options::ReadWrite) -> Self {
        Self::new()
            .set_retry_transaction(value.retry_transaction)
    }
}

impl std::convert::From<crate::model::transaction_options::read_only::ConsistencySelector> for transaction_options::read_only::ConsistencySelector {
    fn from(value: crate::model::transaction_options::read_only::ConsistencySelector) -> Self {
        use crate::model::transaction_options::read_only::ConsistencySelector as V;
        match value {
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<transaction_options::read_only::ConsistencySelector> for crate::model::transaction_options::read_only::ConsistencySelector {
    fn from(value: transaction_options::read_only::ConsistencySelector) -> Self {
        use transaction_options::read_only::ConsistencySelector as V;
        match value {
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::transaction_options::ReadOnly> for transaction_options::ReadOnly {
    fn from(value: crate::model::transaction_options::ReadOnly) -> Self {
        Self {
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<transaction_options::ReadOnly> for crate::model::transaction_options::ReadOnly {
    fn from(value: transaction_options::ReadOnly) -> Self {
        Self::new()
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::transaction_options::Mode> for transaction_options::Mode {
    fn from(value: crate::model::transaction_options::Mode) -> Self {
        use crate::model::transaction_options::Mode as V;
        match value {
            V::ReadOnly(v) => Self::ReadOnly((*v).into()),
            V::ReadWrite(v) => Self::ReadWrite((*v).into()),
        }
    }
}

impl std::convert::From<transaction_options::Mode> for crate::model::transaction_options::Mode {
    fn from(value: transaction_options::Mode) -> Self {
        use transaction_options::Mode as V;
        match value {
            V::ReadOnly(v) => Self::ReadOnly(Box::new(v.into())),
            V::ReadWrite(v) => Self::ReadWrite(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::TransactionOptions> for TransactionOptions {
    fn from(value: crate::model::TransactionOptions) -> Self {
        Self {
            mode: value.mode.map(|v| v.into()),
        }
    }
}

impl std::convert::From<TransactionOptions> for crate::model::TransactionOptions {
    fn from(value: TransactionOptions) -> Self {
        Self::new()
            .set_mode(value.mode.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::Document> for Document {
    fn from(value: crate::model::Document) -> Self {
        Self {
            name: value.name.into(),
            create_time: value.create_time.map(|v| v.into()),
            update_time: value.update_time.map(|v| v.into()),
            fields: value.fields.into_iter().map(|(k, v)| (k.into(), v.into())).collect(),
        }
    }
}

impl std::convert::From<Document> for crate::model::Document {
    fn from(value: Document) -> Self {
        Self::new()
            .set_name(value.name)
            .set_fields(value.fields)
            .set_create_time(value.create_time.map(|v| v.into()))
            .set_update_time(value.update_time.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::value::ValueType> for value::ValueType {
    fn from(value: crate::model::value::ValueType) -> Self {
        use crate::model::value::ValueType as V;
        match value {
            V::NullValue(v) => Self::NullValue(v.into()),
            V::BooleanValue(v) => Self::BooleanValue(v.into()),
            V::IntegerValue(v) => Self::IntegerValue(v.into()),
            V::DoubleValue(v) => Self::DoubleValue(v.into()),
            V::TimestampValue(v) => Self::TimestampValue((*v).into()),
            V::StringValue(v) => Self::StringValue(v.into()),
            V::BytesValue(v) => Self::BytesValue(v.into()),
            V::ReferenceValue(v) => Self::ReferenceValue(v.into()),
            V::GeoPointValue(v) => Self::GeoPointValue((*v).into()),
            V::ArrayValue(v) => Self::ArrayValue((*v).into()),
            V::MapValue(v) => Self::MapValue((*v).into()),
        }
    }
}

impl std::convert::From<value::ValueType> for crate::model::value::ValueType {
    fn from(value: value::ValueType) -> Self {
        use value::ValueType as V;
        match value {
            V::NullValue(v) => Self::NullValue(v.into()),
            V::BooleanValue(v) => Self::BooleanValue(v.into()),
            V::IntegerValue(v) => Self::IntegerValue(v.into()),
            V::DoubleValue(v) => Self::DoubleValue(v.into()),
            V::TimestampValue(v) => Self::TimestampValue(Box::new(v.into())),
            V::StringValue(v) => Self::StringValue(v.into()),
            V::BytesValue(v) => Self::BytesValue(v.into()),
            V::ReferenceValue(v) => Self::ReferenceValue(v.into()),
            V::GeoPointValue(v) => Self::GeoPointValue(Box::new(v.into())),
            V::ArrayValue(v) => Self::ArrayValue(Box::new(v.into())),
            V::MapValue(v) => Self::MapValue(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::Value> for Value {
    fn from(value: crate::model::Value) -> Self {
        Self {
            value_type: value.value_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<Value> for crate::model::Value {
    fn from(value: Value) -> Self {
        Self::new()
            .set_value_type(value.value_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::ArrayValue> for ArrayValue {
    fn from(value: crate::model::ArrayValue) -> Self {
        Self {
            values: value.values.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<ArrayValue> for crate::model::ArrayValue {
    fn from(value: ArrayValue) -> Self {
        Self::new()
            .set_values(value.values)
    }
}

impl std::convert::From<crate::model::MapValue> for MapValue {
    fn from(value: crate::model::MapValue) -> Self {
        Self {
            fields: value.fields.into_iter().map(|(k, v)| (k.into(), v.into())).collect(),
        }
    }
}

impl std::convert::From<MapValue> for crate::model::MapValue {
    fn from(value: MapValue) -> Self {
        Self::new()
            .set_fields(value.fields)
    }
}

impl std::convert::From<crate::model::get_document_request::ConsistencySelector> for get_document_request::ConsistencySelector {
    fn from(value: crate::model::get_document_request::ConsistencySelector) -> Self {
        use crate::model::get_document_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<get_document_request::ConsistencySelector> for crate::model::get_document_request::ConsistencySelector {
    fn from(value: get_document_request::ConsistencySelector) -> Self {
        use get_document_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::GetDocumentRequest> for GetDocumentRequest {
    fn from(value: crate::model::GetDocumentRequest) -> Self {
        Self {
            name: value.name.into(),
            mask: value.mask.map(|v| v.into()),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<GetDocumentRequest> for crate::model::GetDocumentRequest {
    fn from(value: GetDocumentRequest) -> Self {
        Self::new()
            .set_name(value.name)
            .set_mask(value.mask.map(|v| v.into()))
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::list_documents_request::ConsistencySelector> for list_documents_request::ConsistencySelector {
    fn from(value: crate::model::list_documents_request::ConsistencySelector) -> Self {
        use crate::model::list_documents_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<list_documents_request::ConsistencySelector> for crate::model::list_documents_request::ConsistencySelector {
    fn from(value: list_documents_request::ConsistencySelector) -> Self {
        use list_documents_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::ListDocumentsRequest> for ListDocumentsRequest {
    fn from(value: crate::model::ListDocumentsRequest) -> Self {
        Self {
            parent: value.parent.into(),
            collection_id: value.collection_id.into(),
            page_size: value.page_size.into(),
            page_token: value.page_token.into(),
            order_by: value.order_by.into(),
            mask: value.mask.map(|v| v.into()),
            show_missing: value.show_missing.into(),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ListDocumentsRequest> for crate::model::ListDocumentsRequest {
    fn from(value: ListDocumentsRequest) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_collection_id(value.collection_id)
            .set_page_size(value.page_size)
            .set_page_token(value.page_token)
            .set_order_by(value.order_by)
            .set_mask(value.mask.map(|v| v.into()))
            .set_show_missing(value.show_missing)
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::ListDocumentsResponse> for ListDocumentsResponse {
    fn from(value: crate::model::ListDocumentsResponse) -> Self {
        Self {
            next_page_token: value.next_page_token.into(),
            documents: value.documents.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<ListDocumentsResponse> for crate::model::ListDocumentsResponse {
    fn from(value: ListDocumentsResponse) -> Self {
        Self::new()
            .set_documents(value.documents)
            .set_next_page_token(value.next_page_token)
    }
}

impl std::convert::From<crate::model::CreateDocumentRequest> for CreateDocumentRequest {
    fn from(value: crate::model::CreateDocumentRequest) -> Self {
        Self {
            parent: value.parent.into(),
            collection_id: value.collection_id.into(),
            document_id: value.document_id.into(),
            document: value.document.map(|v| v.into()),
            mask: value.mask.map(|v| v.into()),
        }
    }
}

impl std::convert::From<CreateDocumentRequest> for crate::model::CreateDocumentRequest {
    fn from(value: CreateDocumentRequest) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_collection_id(value.collection_id)
            .set_document_id(value.document_id)
            .set_document(value.document.map(|v| v.into()))
            .set_mask(value.mask.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::UpdateDocumentRequest> for UpdateDocumentRequest {
    fn from(value: crate::model::UpdateDocumentRequest) -> Self {
        Self {
            document: value.document.map(|v| v.into()),
            update_mask: value.update_mask.map(|v| v.into()),
            mask: value.mask.map(|v| v.into()),
            current_document: value.current_document.map(|v| v.into()),
        }
    }
}

impl std::convert::From<UpdateDocumentRequest> for crate::model::UpdateDocumentRequest {
    fn from(value: UpdateDocumentRequest) -> Self {
        Self::new()
            .set_document(value.document.map(|v| v.into()))
            .set_update_mask(value.update_mask.map(|v| v.into()))
            .set_mask(value.mask.map(|v| v.into()))
            .set_current_document(value.current_document.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::DeleteDocumentRequest> for DeleteDocumentRequest {
    fn from(value: crate::model::DeleteDocumentRequest) -> Self {
        Self {
            name: value.name.into(),
            current_document: value.current_document.map(|v| v.into()),
        }
    }
}

impl std::convert::From<DeleteDocumentRequest> for crate::model::DeleteDocumentRequest {
    fn from(value: DeleteDocumentRequest) -> Self {
        Self::new()
            .set_name(value.name)
            .set_current_document(value.current_document.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::batch_get_documents_request::ConsistencySelector> for batch_get_documents_request::ConsistencySelector {
    fn from(value: crate::model::batch_get_documents_request::ConsistencySelector) -> Self {
        use crate::model::batch_get_documents_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::NewTransaction(v) => Self::NewTransaction((*v).into()),
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<batch_get_documents_request::ConsistencySelector> for crate::model::batch_get_documents_request::ConsistencySelector {
    fn from(value: batch_get_documents_request::ConsistencySelector) -> Self {
        use batch_get_documents_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::NewTransaction(v) => Self::NewTransaction(Box::new(v.into())),
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::BatchGetDocumentsRequest> for BatchGetDocumentsRequest {
    fn from(value: crate::model::BatchGetDocumentsRequest) -> Self {
        Self {
            database: value.database.into(),
            mask: value.mask.map(|v| v.into()),
            documents: value.documents.into_iter().map(|v| v.into()).collect(),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<BatchGetDocumentsRequest> for crate::model::BatchGetDocumentsRequest {
    fn from(value: BatchGetDocumentsRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_documents(value.documents)
            .set_mask(value.mask.map(|v| v.into()))
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::batch_get_documents_response::Result> for batch_get_documents_response::Result {
    fn from(value: crate::model::batch_get_documents_response::Result) -> Self {
        use crate::model::batch_get_documents_response::Result as V;
        match value {
            V::Found(v) => Self::Found((*v).into()),
            V::Missing(v) => Self::Missing(v.into()),
        }
    }
}

impl std::convert::From<batch_get_documents_response::Result> for crate::model::batch_get_documents_response::Result {
    fn from(value: batch_get_documents_response::Result) -> Self {
        use batch_get_documents_response::Result as V;
        match value {
            V::Found(v) => Self::Found(Box::new(v.into())),
            V::Missing(v) => Self::Missing(v.into()),
        }
    }
}

impl std::convert::From<crate::model::BatchGetDocumentsResponse> for BatchGetDocumentsResponse {
    fn from(value: crate::model::BatchGetDocumentsResponse) -> Self {
        Self {
            transaction: value.transaction.into(),
            read_time: value.read_time.map(|v| v.into()),
            result: value.result.map(|v| v.into()),
        }
    }
}

impl std::convert::From<BatchGetDocumentsResponse> for crate::model::BatchGetDocumentsResponse {
    fn from(value: BatchGetDocumentsResponse) -> Self {
        Self::new()
            .set_transaction(value.transaction)
            .set_read_time(value.read_time.map(|v| v.into()))
            .set_result(value.result.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::BeginTransactionRequest> for BeginTransactionRequest {
    fn from(value: crate::model::BeginTransactionRequest) -> Self {
        Self {
            database: value.database.into(),
            options: value.options.map(|v| v.into()),
        }
    }
}

impl std::convert::From<BeginTransactionRequest> for crate::model::BeginTransactionRequest {
    fn from(value: BeginTransactionRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_options(value.options.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::BeginTransactionResponse> for BeginTransactionResponse {
    fn from(value: crate::model::BeginTransactionResponse) -> Self {
        Self {
            transaction: value.transaction.into(),
        }
    }
}

impl std::convert::From<BeginTransactionResponse> for crate::model::BeginTransactionResponse {
    fn from(value: BeginTransactionResponse) -> Self {
        Self::new()
            .set_transaction(value.transaction)
    }
}

impl std::convert::From<crate::model::CommitRequest> for CommitRequest {
    fn from(value: crate::model::CommitRequest) -> Self {
        Self {
            database: value.database.into(),
            transaction: value.transaction.into(),
            writes: value.writes.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<CommitRequest> for crate::model::CommitRequest {
    fn from(value: CommitRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_writes(value.writes)
            .set_transaction(value.transaction)
    }
}

impl std::convert::From<crate::model::CommitResponse> for CommitResponse {
    fn from(value: crate::model::CommitResponse) -> Self {
        Self {
            commit_time: value.commit_time.map(|v| v.into()),
            write_results: value.write_results.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<CommitResponse> for crate::model::CommitResponse {
    fn from(value: CommitResponse) -> Self {
        Self::new()
            .set_write_results(value.write_results)
            .set_commit_time(value.commit_time.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::RollbackRequest> for RollbackRequest {
    fn from(value: crate::model::RollbackRequest) -> Self {
        Self {
            database: value.database.into(),
            transaction: value.transaction.into(),
        }
    }
}

impl std::convert::From<RollbackRequest> for crate::model::RollbackRequest {
    fn from(value: RollbackRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_transaction(value.transaction)
    }
}

impl std::convert::From<crate::model::run_query_request::QueryType> for run_query_request::QueryType {
    fn from(value: crate::model::run_query_request::QueryType) -> Self {
        use crate::model::run_query_request::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery((*v).into()),
        }
    }
}

impl std::convert::From<run_query_request::QueryType> for crate::model::run_query_request::QueryType {
    fn from(value: run_query_request::QueryType) -> Self {
        use run_query_request::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::run_query_request::ConsistencySelector> for run_query_request::ConsistencySelector {
    fn from(value: crate::model::run_query_request::ConsistencySelector) -> Self {
        use crate::model::run_query_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::NewTransaction(v) => Self::NewTransaction((*v).into()),
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<run_query_request::ConsistencySelector> for crate::model::run_query_request::ConsistencySelector {
    fn from(value: run_query_request::ConsistencySelector) -> Self {
        use run_query_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::NewTransaction(v) => Self::NewTransaction(Box::new(v.into())),
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::RunQueryRequest> for RunQueryRequest {
    fn from(value: crate::model::RunQueryRequest) -> Self {
        Self {
            parent: value.parent.into(),
            explain_options: value.explain_options.map(|v| v.into()),
            query_type: value.query_type.map(|v| v.into()),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<RunQueryRequest> for crate::model::RunQueryRequest {
    fn from(value: RunQueryRequest) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_explain_options(value.explain_options.map(|v| v.into()))
            .set_query_type(value.query_type.map(|v| v.into()))
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::run_query_response::ContinuationSelector> for run_query_response::ContinuationSelector {
    fn from(value: crate::model::run_query_response::ContinuationSelector) -> Self {
        use crate::model::run_query_response::ContinuationSelector as V;
        match value {
            V::Done(v) => Self::Done(v.into()),
        }
    }
}

impl std::convert::From<run_query_response::ContinuationSelector> for crate::model::run_query_response::ContinuationSelector {
    fn from(value: run_query_response::ContinuationSelector) -> Self {
        use run_query_response::ContinuationSelector as V;
        match value {
            V::Done(v) => Self::Done(v.into()),
        }
    }
}

impl std::convert::From<crate::model::RunQueryResponse> for RunQueryResponse {
    fn from(value: crate::model::RunQueryResponse) -> Self {
        Self {
            transaction: value.transaction.into(),
            document: value.document.map(|v| v.into()),
            read_time: value.read_time.map(|v| v.into()),
            skipped_results: value.skipped_results.into(),
            explain_metrics: value.explain_metrics.map(|v| v.into()),
            continuation_selector: value.continuation_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<RunQueryResponse> for crate::model::RunQueryResponse {
    fn from(value: RunQueryResponse) -> Self {
        Self::new()
            .set_transaction(value.transaction)
            .set_document(value.document.map(|v| v.into()))
            .set_read_time(value.read_time.map(|v| v.into()))
            .set_skipped_results(value.skipped_results)
            .set_explain_metrics(value.explain_metrics.map(|v| v.into()))
            .set_continuation_selector(value.continuation_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::run_aggregation_query_request::QueryType> for run_aggregation_query_request::QueryType {
    fn from(value: crate::model::run_aggregation_query_request::QueryType) -> Self {
        use crate::model::run_aggregation_query_request::QueryType as V;
        match value {
            V::StructuredAggregationQuery(v) => Self::StructuredAggregationQuery((*v).into()),
        }
    }
}

impl std::convert::From<run_aggregation_query_request::QueryType> for crate::model::run_aggregation_query_request::QueryType {
    fn from(value: run_aggregation_query_request::QueryType) -> Self {
        use run_aggregation_query_request::QueryType as V;
        match value {
            V::StructuredAggregationQuery(v) => Self::StructuredAggregationQuery(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::run_aggregation_query_request::ConsistencySelector> for run_aggregation_query_request::ConsistencySelector {
    fn from(value: crate::model::run_aggregation_query_request::ConsistencySelector) -> Self {
        use crate::model::run_aggregation_query_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::NewTransaction(v) => Self::NewTransaction((*v).into()),
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<run_aggregation_query_request::ConsistencySelector> for crate::model::run_aggregation_query_request::ConsistencySelector {
    fn from(value: run_aggregation_query_request::ConsistencySelector) -> Self {
        use run_aggregation_query_request::ConsistencySelector as V;
        match value {
            V::Transaction(v) => Self::Transaction(v.into()),
            V::NewTransaction(v) => Self::NewTransaction(Box::new(v.into())),
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::RunAggregationQueryRequest> for RunAggregationQueryRequest {
    fn from(value: crate::model::RunAggregationQueryRequest) -> Self {
        Self {
            parent: value.parent.into(),
            explain_options: value.explain_options.map(|v| v.into()),
            query_type: value.query_type.map(|v| v.into()),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<RunAggregationQueryRequest> for crate::model::RunAggregationQueryRequest {
    fn from(value: RunAggregationQueryRequest) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_explain_options(value.explain_options.map(|v| v.into()))
            .set_query_type(value.query_type.map(|v| v.into()))
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::RunAggregationQueryResponse> for RunAggregationQueryResponse {
    fn from(value: crate::model::RunAggregationQueryResponse) -> Self {
        Self {
            result: value.result.map(|v| v.into()),
            transaction: value.transaction.into(),
            read_time: value.read_time.map(|v| v.into()),
            explain_metrics: value.explain_metrics.map(|v| v.into()),
        }
    }
}

impl std::convert::From<RunAggregationQueryResponse> for crate::model::RunAggregationQueryResponse {
    fn from(value: RunAggregationQueryResponse) -> Self {
        Self::new()
            .set_result(value.result.map(|v| v.into()))
            .set_transaction(value.transaction)
            .set_read_time(value.read_time.map(|v| v.into()))
            .set_explain_metrics(value.explain_metrics.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::partition_query_request::QueryType> for partition_query_request::QueryType {
    fn from(value: crate::model::partition_query_request::QueryType) -> Self {
        use crate::model::partition_query_request::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery((*v).into()),
        }
    }
}

impl std::convert::From<partition_query_request::QueryType> for crate::model::partition_query_request::QueryType {
    fn from(value: partition_query_request::QueryType) -> Self {
        use partition_query_request::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::partition_query_request::ConsistencySelector> for partition_query_request::ConsistencySelector {
    fn from(value: crate::model::partition_query_request::ConsistencySelector) -> Self {
        use crate::model::partition_query_request::ConsistencySelector as V;
        match value {
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<partition_query_request::ConsistencySelector> for crate::model::partition_query_request::ConsistencySelector {
    fn from(value: partition_query_request::ConsistencySelector) -> Self {
        use partition_query_request::ConsistencySelector as V;
        match value {
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::PartitionQueryRequest> for PartitionQueryRequest {
    fn from(value: crate::model::PartitionQueryRequest) -> Self {
        Self {
            parent: value.parent.into(),
            partition_count: value.partition_count.into(),
            page_token: value.page_token.into(),
            page_size: value.page_size.into(),
            query_type: value.query_type.map(|v| v.into()),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<PartitionQueryRequest> for crate::model::PartitionQueryRequest {
    fn from(value: PartitionQueryRequest) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_partition_count(value.partition_count)
            .set_page_token(value.page_token)
            .set_page_size(value.page_size)
            .set_query_type(value.query_type.map(|v| v.into()))
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::PartitionQueryResponse> for PartitionQueryResponse {
    fn from(value: crate::model::PartitionQueryResponse) -> Self {
        Self {
            next_page_token: value.next_page_token.into(),
            partitions: value.partitions.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<PartitionQueryResponse> for crate::model::PartitionQueryResponse {
    fn from(value: PartitionQueryResponse) -> Self {
        Self::new()
            .set_partitions(value.partitions)
            .set_next_page_token(value.next_page_token)
    }
}

impl std::convert::From<crate::model::WriteRequest> for WriteRequest {
    fn from(value: crate::model::WriteRequest) -> Self {
        Self {
            database: value.database.into(),
            stream_id: value.stream_id.into(),
            stream_token: value.stream_token.into(),
            writes: value.writes.into_iter().map(|v| v.into()).collect(),
            labels: value.labels.into_iter().map(|(k, v)| (k.into(), v.into())).collect(),
        }
    }
}

impl std::convert::From<WriteRequest> for crate::model::WriteRequest {
    fn from(value: WriteRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_stream_id(value.stream_id)
            .set_writes(value.writes)
            .set_stream_token(value.stream_token)
            .set_labels(value.labels)
    }
}

impl std::convert::From<crate::model::WriteResponse> for WriteResponse {
    fn from(value: crate::model::WriteResponse) -> Self {
        Self {
            stream_id: value.stream_id.into(),
            stream_token: value.stream_token.into(),
            commit_time: value.commit_time.map(|v| v.into()),
            write_results: value.write_results.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<WriteResponse> for crate::model::WriteResponse {
    fn from(value: WriteResponse) -> Self {
        Self::new()
            .set_stream_id(value.stream_id)
            .set_stream_token(value.stream_token)
            .set_write_results(value.write_results)
            .set_commit_time(value.commit_time.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::listen_request::TargetChange> for listen_request::TargetChange {
    fn from(value: crate::model::listen_request::TargetChange) -> Self {
        use crate::model::listen_request::TargetChange as V;
        match value {
            V::AddTarget(v) => Self::AddTarget((*v).into()),
            V::RemoveTarget(v) => Self::RemoveTarget(v.into()),
        }
    }
}

impl std::convert::From<listen_request::TargetChange> for crate::model::listen_request::TargetChange {
    fn from(value: listen_request::TargetChange) -> Self {
        use listen_request::TargetChange as V;
        match value {
            V::AddTarget(v) => Self::AddTarget(Box::new(v.into())),
            V::RemoveTarget(v) => Self::RemoveTarget(v.into()),
        }
    }
}

impl std::convert::From<crate::model::ListenRequest> for ListenRequest {
    fn from(value: crate::model::ListenRequest) -> Self {
        Self {
            database: value.database.into(),
            labels: value.labels.into_iter().map(|(k, v)| (k.into(), v.into())).collect(),
            target_change: value.target_change.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ListenRequest> for crate::model::ListenRequest {
    fn from(value: ListenRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_labels(value.labels)
            .set_target_change(value.target_change.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::listen_response::ResponseType> for listen_response::ResponseType {
    fn from(value: crate::model::listen_response::ResponseType) -> Self {
        use crate::model::listen_response::ResponseType as V;
        match value {
            V::TargetChange(v) => Self::TargetChange((*v).into()),
            V::DocumentChange(v) => Self::DocumentChange((*v).into()),
            V::DocumentDelete(v) => Self::DocumentDelete((*v).into()),
            V::DocumentRemove(v) => Self::DocumentRemove((*v).into()),
            V::Filter(v) => Self::Filter((*v).into()),
        }
    }
}

impl std::convert::From<listen_response::ResponseType> for crate::model::listen_response::ResponseType {
    fn from(value: listen_response::ResponseType) -> Self {
        use listen_response::ResponseType as V;
        match value {
            V::TargetChange(v) => Self::TargetChange(Box::new(v.into())),
            V::DocumentChange(v) => Self::DocumentChange(Box::new(v.into())),
            V::DocumentDelete(v) => Self::DocumentDelete(Box::new(v.into())),
            V::DocumentRemove(v) => Self::DocumentRemove(Box::new(v.into())),
            V::Filter(v) => Self::Filter(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::ListenResponse> for ListenResponse {
    fn from(value: crate::model::ListenResponse) -> Self {
        Self {
            response_type: value.response_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ListenResponse> for crate::model::ListenResponse {
    fn from(value: ListenResponse) -> Self {
        Self::new()
            .set_response_type(value.response_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::target::DocumentsTarget> for target::DocumentsTarget {
    fn from(value: crate::model::target::DocumentsTarget) -> Self {
        Self {
            documents: value.documents.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<target::DocumentsTarget> for crate::model::target::DocumentsTarget {
    fn from(value: target::DocumentsTarget) -> Self {
        Self::new()
            .set_documents(value.documents)
    }
}

impl std::convert::From<crate::model::target::query_target::QueryType> for target::query_target::QueryType {
    fn from(value: crate::model::target::query_target::QueryType) -> Self {
        use crate::model::target::query_target::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery((*v).into()),
        }
    }
}

impl std::convert::From<target::query_target::QueryType> for crate::model::target::query_target::QueryType {
    fn from(value: target::query_target::QueryType) -> Self {
        use target::query_target::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::target::QueryTarget> for target::QueryTarget {
    fn from(value: crate::model::target::QueryTarget) -> Self {
        Self {
            parent: value.parent.into(),
            query_type: value.query_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<target::QueryTarget> for crate::model::target::QueryTarget {
    fn from(value: target::QueryTarget) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_query_type(value.query_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::target::TargetType> for target::TargetType {
    fn from(value: crate::model::target::TargetType) -> Self {
        use crate::model::target::TargetType as V;
        match value {
            V::Query(v) => Self::Query((*v).into()),
            V::Documents(v) => Self::Documents((*v).into()),
        }
    }
}

impl std::convert::From<target::TargetType> for crate::model::target::TargetType {
    fn from(value: target::TargetType) -> Self {
        use target::TargetType as V;
        match value {
            V::Query(v) => Self::Query(Box::new(v.into())),
            V::Documents(v) => Self::Documents(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::target::ResumeType> for target::ResumeType {
    fn from(value: crate::model::target::ResumeType) -> Self {
        use crate::model::target::ResumeType as V;
        match value {
            V::ResumeToken(v) => Self::ResumeToken(v.into()),
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<target::ResumeType> for crate::model::target::ResumeType {
    fn from(value: target::ResumeType) -> Self {
        use target::ResumeType as V;
        match value {
            V::ResumeToken(v) => Self::ResumeToken(v.into()),
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::Target> for Target {
    fn from(value: crate::model::Target) -> Self {
        Self {
            target_id: value.target_id.into(),
            once: value.once.into(),
            expected_count: value.expected_count.map(|v| v.into()),
            target_type: value.target_type.map(|v| v.into()),
            resume_type: value.resume_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<Target> for crate::model::Target {
    fn from(value: Target) -> Self {
        Self::new()
            .set_target_id(value.target_id)
            .set_once(value.once)
            .set_expected_count(value.expected_count.map(|v| v.into()))
            .set_target_type(value.target_type.map(|v| v.into()))
            .set_resume_type(value.resume_type.map(|v| v.into()))
    }
}

impl std::convert::TryFrom<crate::model::target_change::TargetChangeType> for target_change::TargetChangeType {
    type Error = crate::Error;

    fn try_from(value: crate::model::target_change::TargetChangeType) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::target_change::TargetChangeType value"))
    }
}

impl std::convert::From<target_change::TargetChangeType> for crate::model::target_change::TargetChangeType {
    fn from(value: target_change::TargetChangeType) -> Self {
        Self::new(value.as_str_name())
    }
} 

impl std::convert::From<crate::model::TargetChange> for TargetChange {
    fn from(value: crate::model::TargetChange) -> Self {
        Self {
            target_change_type: value.target_change_type.into(),
            cause: value.cause.map(|v| v.into()),
            resume_token: value.resume_token.into(),
            read_time: value.read_time.map(|v| v.into()),
            target_ids: value.target_ids.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<TargetChange> for crate::model::TargetChange {
    fn from(value: TargetChange) -> Self {
        Self::new()
            .set_target_change_type(value.target_change_type)
            .set_target_ids(value.target_ids)
            .set_cause(value.cause.map(|v| v.into()))
            .set_resume_token(value.resume_token)
            .set_read_time(value.read_time.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::list_collection_ids_request::ConsistencySelector> for list_collection_ids_request::ConsistencySelector {
    fn from(value: crate::model::list_collection_ids_request::ConsistencySelector) -> Self {
        use crate::model::list_collection_ids_request::ConsistencySelector as V;
        match value {
            V::ReadTime(v) => Self::ReadTime((*v).into()),
        }
    }
}

impl std::convert::From<list_collection_ids_request::ConsistencySelector> for crate::model::list_collection_ids_request::ConsistencySelector {
    fn from(value: list_collection_ids_request::ConsistencySelector) -> Self {
        use list_collection_ids_request::ConsistencySelector as V;
        match value {
            V::ReadTime(v) => Self::ReadTime(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::ListCollectionIdsRequest> for ListCollectionIdsRequest {
    fn from(value: crate::model::ListCollectionIdsRequest) -> Self {
        Self {
            parent: value.parent.into(),
            page_size: value.page_size.into(),
            page_token: value.page_token.into(),
            consistency_selector: value.consistency_selector.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ListCollectionIdsRequest> for crate::model::ListCollectionIdsRequest {
    fn from(value: ListCollectionIdsRequest) -> Self {
        Self::new()
            .set_parent(value.parent)
            .set_page_size(value.page_size)
            .set_page_token(value.page_token)
            .set_consistency_selector(value.consistency_selector.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::ListCollectionIdsResponse> for ListCollectionIdsResponse {
    fn from(value: crate::model::ListCollectionIdsResponse) -> Self {
        Self {
            next_page_token: value.next_page_token.into(),
            collection_ids: value.collection_ids.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<ListCollectionIdsResponse> for crate::model::ListCollectionIdsResponse {
    fn from(value: ListCollectionIdsResponse) -> Self {
        Self::new()
            .set_collection_ids(value.collection_ids)
            .set_next_page_token(value.next_page_token)
    }
}

impl std::convert::From<crate::model::BatchWriteRequest> for BatchWriteRequest {
    fn from(value: crate::model::BatchWriteRequest) -> Self {
        Self {
            database: value.database.into(),
            writes: value.writes.into_iter().map(|v| v.into()).collect(),
            labels: value.labels.into_iter().map(|(k, v)| (k.into(), v.into())).collect(),
        }
    }
}

impl std::convert::From<BatchWriteRequest> for crate::model::BatchWriteRequest {
    fn from(value: BatchWriteRequest) -> Self {
        Self::new()
            .set_database(value.database)
            .set_writes(value.writes)
            .set_labels(value.labels)
    }
}

impl std::convert::From<crate::model::BatchWriteResponse> for BatchWriteResponse {
    fn from(value: crate::model::BatchWriteResponse) -> Self {
        Self {
            write_results: value.write_results.into_iter().map(|v| v.into()).collect(),
            status: value.status.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<BatchWriteResponse> for crate::model::BatchWriteResponse {
    fn from(value: BatchWriteResponse) -> Self {
        Self::new()
            .set_write_results(value.write_results)
            .set_status(value.status)
    }
}

impl std::convert::From<crate::model::structured_query::CollectionSelector> for structured_query::CollectionSelector {
    fn from(value: crate::model::structured_query::CollectionSelector) -> Self {
        Self {
            collection_id: value.collection_id.into(),
            all_descendants: value.all_descendants.into(),
        }
    }
}

impl std::convert::From<structured_query::CollectionSelector> for crate::model::structured_query::CollectionSelector {
    fn from(value: structured_query::CollectionSelector) -> Self {
        Self::new()
            .set_collection_id(value.collection_id)
            .set_all_descendants(value.all_descendants)
    }
}

impl std::convert::From<crate::model::structured_query::filter::FilterType> for structured_query::filter::FilterType {
    fn from(value: crate::model::structured_query::filter::FilterType) -> Self {
        use crate::model::structured_query::filter::FilterType as V;
        match value {
            V::CompositeFilter(v) => Self::CompositeFilter((*v).into()),
            V::FieldFilter(v) => Self::FieldFilter((*v).into()),
            V::UnaryFilter(v) => Self::UnaryFilter((*v).into()),
        }
    }
}

impl std::convert::From<structured_query::filter::FilterType> for crate::model::structured_query::filter::FilterType {
    fn from(value: structured_query::filter::FilterType) -> Self {
        use structured_query::filter::FilterType as V;
        match value {
            V::CompositeFilter(v) => Self::CompositeFilter(Box::new(v.into())),
            V::FieldFilter(v) => Self::FieldFilter(Box::new(v.into())),
            V::UnaryFilter(v) => Self::UnaryFilter(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::structured_query::Filter> for structured_query::Filter {
    fn from(value: crate::model::structured_query::Filter) -> Self {
        Self {
            filter_type: value.filter_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_query::Filter> for crate::model::structured_query::Filter {
    fn from(value: structured_query::Filter) -> Self {
        Self::new()
            .set_filter_type(value.filter_type.map(|v| v.into()))
    }
}

impl std::convert::TryFrom<crate::model::structured_query::composite_filter::Operator> for structured_query::composite_filter::Operator {
    type Error = crate::Error;

    fn try_from(value: crate::model::structured_query::composite_filter::Operator) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::structured_query::composite_filter::Operator value"))
    }
}

impl std::convert::From<structured_query::composite_filter::Operator> for crate::model::structured_query::composite_filter::Operator {
    fn from(value: structured_query::composite_filter::Operator) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<crate::model::structured_query::CompositeFilter> for structured_query::CompositeFilter {
    fn from(value: crate::model::structured_query::CompositeFilter) -> Self {
        Self {
            op: value.op.into(),
            filters: value.filters.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<structured_query::CompositeFilter> for crate::model::structured_query::CompositeFilter {
    fn from(value: structured_query::CompositeFilter) -> Self {
        Self::new()
            .set_op(value.op)
            .set_filters(value.filters)
    }
}

impl std::convert::TryFrom<crate::model::structured_query::field_filter::Operator> for structured_query::field_filter::Operator {
    type Error = crate::Error;

    fn try_from(value: crate::model::structured_query::field_filter::Operator) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::structured_query::field_filter::Operator value"))
    }
}

impl std::convert::From<structured_query::field_filter::Operator> for crate::model::structured_query::field_filter::Operator {
    fn from(value: structured_query::field_filter::Operator) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<crate::model::structured_query::FieldFilter> for structured_query::FieldFilter {
    fn from(value: crate::model::structured_query::FieldFilter) -> Self {
        Self {
            field: value.field.map(|v| v.into()),
            op: value.op.into(),
            value: value.value.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_query::FieldFilter> for crate::model::structured_query::FieldFilter {
    fn from(value: structured_query::FieldFilter) -> Self {
        Self::new()
            .set_field(value.field.map(|v| v.into()))
            .set_op(value.op)
            .set_value(value.value.map(|v| v.into()))
    }
}

impl std::convert::TryFrom<crate::model::structured_query::unary_filter::Operator> for structured_query::unary_filter::Operator {
    type Error = crate::Error;

    fn try_from(value: crate::model::structured_query::unary_filter::Operator) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::structured_query::unary_filter::Operator value"))
    }
}

impl std::convert::From<structured_query::unary_filter::Operator> for crate::model::structured_query::unary_filter::Operator {
    fn from(value: structured_query::unary_filter::Operator) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<crate::model::structured_query::unary_filter::OperandType> for structured_query::unary_filter::OperandType {
    fn from(value: crate::model::structured_query::unary_filter::OperandType) -> Self {
        use crate::model::structured_query::unary_filter::OperandType as V;
        match value {
            V::Field(v) => Self::Field((*v).into()),
        }
    }
}

impl std::convert::From<structured_query::unary_filter::OperandType> for crate::model::structured_query::unary_filter::OperandType {
    fn from(value: structured_query::unary_filter::OperandType) -> Self {
        use structured_query::unary_filter::OperandType as V;
        match value {
            V::Field(v) => Self::Field(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::structured_query::UnaryFilter> for structured_query::UnaryFilter {
    fn from(value: crate::model::structured_query::UnaryFilter) -> Self {
        Self {
            op: value.op.into(),
            operand_type: value.operand_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_query::UnaryFilter> for crate::model::structured_query::UnaryFilter {
    fn from(value: structured_query::UnaryFilter) -> Self {
        Self::new()
            .set_op(value.op)
            .set_operand_type(value.operand_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::structured_query::Order> for structured_query::Order {
    fn from(value: crate::model::structured_query::Order) -> Self {
        Self {
            field: value.field.map(|v| v.into()),
            direction: value.direction.into(),
        }
    }
}

impl std::convert::From<structured_query::Order> for crate::model::structured_query::Order {
    fn from(value: structured_query::Order) -> Self {
        Self::new()
            .set_field(value.field.map(|v| v.into()))
            .set_direction(value.direction)
    }
}

impl std::convert::From<crate::model::structured_query::FieldReference> for structured_query::FieldReference {
    fn from(value: crate::model::structured_query::FieldReference) -> Self {
        Self {
            field_path: value.field_path.into(),
        }
    }
}

impl std::convert::From<structured_query::FieldReference> for crate::model::structured_query::FieldReference {
    fn from(value: structured_query::FieldReference) -> Self {
        Self::new()
            .set_field_path(value.field_path)
    }
}

impl std::convert::From<crate::model::structured_query::Projection> for structured_query::Projection {
    fn from(value: crate::model::structured_query::Projection) -> Self {
        Self {
            fields: value.fields.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<structured_query::Projection> for crate::model::structured_query::Projection {
    fn from(value: structured_query::Projection) -> Self {
        Self::new()
            .set_fields(value.fields)
    }
}

impl std::convert::TryFrom<crate::model::structured_query::find_nearest::DistanceMeasure> for structured_query::find_nearest::DistanceMeasure {
    type Error = crate::Error;

    fn try_from(value: crate::model::structured_query::find_nearest::DistanceMeasure) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::structured_query::find_nearest::DistanceMeasure value"))
    }
}

impl std::convert::From<structured_query::find_nearest::DistanceMeasure> for crate::model::structured_query::find_nearest::DistanceMeasure {
    fn from(value: structured_query::find_nearest::DistanceMeasure) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<crate::model::structured_query::FindNearest> for structured_query::FindNearest {
    fn from(value: crate::model::structured_query::FindNearest) -> Self {
        Self {
            vector_field: value.vector_field.map(|v| v.into()),
            query_vector: value.query_vector.map(|v| v.into()),
            distance_measure: value.distance_measure.into(),
            limit: value.limit.map(|v| v.into()),
            distance_result_field: value.distance_result_field.into(),
            distance_threshold: value.distance_threshold.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_query::FindNearest> for crate::model::structured_query::FindNearest {
    fn from(value: structured_query::FindNearest) -> Self {
        Self::new()
            .set_vector_field(value.vector_field.map(|v| v.into()))
            .set_query_vector(value.query_vector.map(|v| v.into()))
            .set_distance_measure(value.distance_measure)
            .set_limit(value.limit.map(|v| v.into()))
            .set_distance_result_field(value.distance_result_field)
            .set_distance_threshold(value.distance_threshold.map(|v| v.into()))
    }
}

impl std::convert::TryFrom<crate::model::structured_query::Direction> for structured_query::Direction {
    type Error = crate::Error;

    fn try_from(value: crate::model::structured_query::Direction) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::structured_query::Direction value"))
    }
}

impl std::convert::From<structured_query::Direction> for crate::model::structured_query::Direction {
    fn from(value: structured_query::Direction) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<crate::model::StructuredQuery> for StructuredQuery {
    fn from(value: crate::model::StructuredQuery) -> Self {
        Self {
            select: value.select.map(|v| v.into()),
            r#where: value.r#where.map(|v| v.into()),
            start_at: value.start_at.map(|v| v.into()),
            end_at: value.end_at.map(|v| v.into()),
            offset: value.offset.into(),
            limit: value.limit.map(|v| v.into()),
            find_nearest: value.find_nearest.map(|v| v.into()),
            from: value.from.into_iter().map(|v| v.into()).collect(),
            order_by: value.order_by.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<StructuredQuery> for crate::model::StructuredQuery {
    fn from(value: StructuredQuery) -> Self {
        Self::new()
            .set_select(value.select.map(|v| v.into()))
            .set_from(value.from)
            .set_where(value.r#where.map(|v| v.into()))
            .set_order_by(value.order_by)
            .set_start_at(value.start_at.map(|v| v.into()))
            .set_end_at(value.end_at.map(|v| v.into()))
            .set_offset(value.offset)
            .set_limit(value.limit.map(|v| v.into()))
            .set_find_nearest(value.find_nearest.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::structured_aggregation_query::aggregation::Count> for structured_aggregation_query::aggregation::Count {
    fn from(value: crate::model::structured_aggregation_query::aggregation::Count) -> Self {
        Self {
            up_to: value.up_to.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_aggregation_query::aggregation::Count> for crate::model::structured_aggregation_query::aggregation::Count {
    fn from(value: structured_aggregation_query::aggregation::Count) -> Self {
        Self::new()
            .set_up_to(value.up_to.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::structured_aggregation_query::aggregation::Sum> for structured_aggregation_query::aggregation::Sum {
    fn from(value: crate::model::structured_aggregation_query::aggregation::Sum) -> Self {
        Self {
            field: value.field.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_aggregation_query::aggregation::Sum> for crate::model::structured_aggregation_query::aggregation::Sum {
    fn from(value: structured_aggregation_query::aggregation::Sum) -> Self {
        Self::new()
            .set_field(value.field.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::structured_aggregation_query::aggregation::Avg> for structured_aggregation_query::aggregation::Avg {
    fn from(value: crate::model::structured_aggregation_query::aggregation::Avg) -> Self {
        Self {
            field: value.field.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_aggregation_query::aggregation::Avg> for crate::model::structured_aggregation_query::aggregation::Avg {
    fn from(value: structured_aggregation_query::aggregation::Avg) -> Self {
        Self::new()
            .set_field(value.field.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::structured_aggregation_query::aggregation::Operator> for structured_aggregation_query::aggregation::Operator {
    fn from(value: crate::model::structured_aggregation_query::aggregation::Operator) -> Self {
        use crate::model::structured_aggregation_query::aggregation::Operator as V;
        match value {
            V::Count(v) => Self::Count((*v).into()),
            V::Sum(v) => Self::Sum((*v).into()),
            V::Avg(v) => Self::Avg((*v).into()),
        }
    }
}

impl std::convert::From<structured_aggregation_query::aggregation::Operator> for crate::model::structured_aggregation_query::aggregation::Operator {
    fn from(value: structured_aggregation_query::aggregation::Operator) -> Self {
        use structured_aggregation_query::aggregation::Operator as V;
        match value {
            V::Count(v) => Self::Count(Box::new(v.into())),
            V::Sum(v) => Self::Sum(Box::new(v.into())),
            V::Avg(v) => Self::Avg(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::structured_aggregation_query::Aggregation> for structured_aggregation_query::Aggregation {
    fn from(value: crate::model::structured_aggregation_query::Aggregation) -> Self {
        Self {
            alias: value.alias.into(),
            operator: value.operator.map(|v| v.into()),
        }
    }
}

impl std::convert::From<structured_aggregation_query::Aggregation> for crate::model::structured_aggregation_query::Aggregation {
    fn from(value: structured_aggregation_query::Aggregation) -> Self {
        Self::new()
            .set_alias(value.alias)
            .set_operator(value.operator.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::structured_aggregation_query::QueryType> for structured_aggregation_query::QueryType {
    fn from(value: crate::model::structured_aggregation_query::QueryType) -> Self {
        use crate::model::structured_aggregation_query::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery((*v).into()),
        }
    }
}

impl std::convert::From<structured_aggregation_query::QueryType> for crate::model::structured_aggregation_query::QueryType {
    fn from(value: structured_aggregation_query::QueryType) -> Self {
        use structured_aggregation_query::QueryType as V;
        match value {
            V::StructuredQuery(v) => Self::StructuredQuery(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::StructuredAggregationQuery> for StructuredAggregationQuery {
    fn from(value: crate::model::StructuredAggregationQuery) -> Self {
        Self {
            aggregations: value.aggregations.into_iter().map(|v| v.into()).collect(),
            query_type: value.query_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<StructuredAggregationQuery> for crate::model::StructuredAggregationQuery {
    fn from(value: StructuredAggregationQuery) -> Self {
        Self::new()
            .set_aggregations(value.aggregations)
            .set_query_type(value.query_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::Cursor> for Cursor {
    fn from(value: crate::model::Cursor) -> Self {
        Self {
            before: value.before.into(),
            values: value.values.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<Cursor> for crate::model::Cursor {
    fn from(value: Cursor) -> Self {
        Self::new()
            .set_values(value.values)
            .set_before(value.before)
    }
}

impl std::convert::From<crate::model::ExplainOptions> for ExplainOptions {
    fn from(value: crate::model::ExplainOptions) -> Self {
        Self {
            analyze: value.analyze.into(),
        }
    }
}

impl std::convert::From<ExplainOptions> for crate::model::ExplainOptions {
    fn from(value: ExplainOptions) -> Self {
        Self::new()
            .set_analyze(value.analyze)
    }
}

impl std::convert::From<crate::model::ExplainMetrics> for ExplainMetrics {
    fn from(value: crate::model::ExplainMetrics) -> Self {
        Self {
            plan_summary: value.plan_summary.map(|v| v.into()),
            execution_stats: value.execution_stats.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ExplainMetrics> for crate::model::ExplainMetrics {
    fn from(value: ExplainMetrics) -> Self {
        Self::new()
            .set_plan_summary(value.plan_summary.map(|v| v.into()))
            .set_execution_stats(value.execution_stats.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::PlanSummary> for PlanSummary {
    fn from(value: crate::model::PlanSummary) -> Self {
        Self {
            indexes_used: value.indexes_used.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<PlanSummary> for crate::model::PlanSummary {
    fn from(value: PlanSummary) -> Self {
        Self::new()
            .set_indexes_used(value.indexes_used)
    }
}

impl std::convert::From<crate::model::ExecutionStats> for ExecutionStats {
    fn from(value: crate::model::ExecutionStats) -> Self {
        Self {
            results_returned: value.results_returned.into(),
            execution_duration: value.execution_duration.map(|v| v.into()),
            read_operations: value.read_operations.into(),
            debug_stats: value.debug_stats.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ExecutionStats> for crate::model::ExecutionStats {
    fn from(value: ExecutionStats) -> Self {
        Self::new()
            .set_results_returned(value.results_returned)
            .set_execution_duration(value.execution_duration.map(|v| v.into()))
            .set_read_operations(value.read_operations)
            .set_debug_stats(value.debug_stats.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::write::Operation> for write::Operation {
    fn from(value: crate::model::write::Operation) -> Self {
        use crate::model::write::Operation as V;
        match value {
            V::Update(v) => Self::Update((*v).into()),
            V::Delete(v) => Self::Delete(v.into()),
            V::Transform(v) => Self::Transform((*v).into()),
        }
    }
}

impl std::convert::From<write::Operation> for crate::model::write::Operation {
    fn from(value: write::Operation) -> Self {
        use write::Operation as V;
        match value {
            V::Update(v) => Self::Update(Box::new(v.into())),
            V::Delete(v) => Self::Delete(v.into()),
            V::Transform(v) => Self::Transform(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::Write> for Write {
    fn from(value: crate::model::Write) -> Self {
        Self {
            update_mask: value.update_mask.map(|v| v.into()),
            current_document: value.current_document.map(|v| v.into()),
            update_transforms: value.update_transforms.into_iter().map(|v| v.into()).collect(),
            operation: value.operation.map(|v| v.into()),
        }
    }
}

impl std::convert::From<Write> for crate::model::Write {
    fn from(value: Write) -> Self {
        Self::new()
            .set_update_mask(value.update_mask.map(|v| v.into()))
            .set_update_transforms(value.update_transforms)
            .set_current_document(value.current_document.map(|v| v.into()))
            .set_operation(value.operation.map(|v| v.into()))
    }
}

impl std::convert::TryFrom<crate::model::document_transform::field_transform::ServerValue> for document_transform::field_transform::ServerValue {
    type Error = crate::Error;

    fn try_from(value: crate::model::document_transform::field_transform::ServerValue) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown crate::model::document_transform::field_transform::ServerValue value"))
    }
}

impl std::convert::From<document_transform::field_transform::ServerValue> for crate::model::document_transform::field_transform::ServerValue {
    fn from(value: document_transform::field_transform::ServerValue) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<crate::model::document_transform::field_transform::TransformType> for document_transform::field_transform::TransformType {
    fn from(value: crate::model::document_transform::field_transform::TransformType) -> Self {
        use crate::model::document_transform::field_transform::TransformType as V;
        match value {
            V::SetToServerValue(v) => Self::SetToServerValue(v.into()),
            V::Increment(v) => Self::Increment((*v).into()),
            V::Maximum(v) => Self::Maximum((*v).into()),
            V::Minimum(v) => Self::Minimum((*v).into()),
            V::AppendMissingElements(v) => Self::AppendMissingElements((*v).into()),
            V::RemoveAllFromArray(v) => Self::RemoveAllFromArray((*v).into()),
        }
    }
}

impl std::convert::From<document_transform::field_transform::TransformType> for crate::model::document_transform::field_transform::TransformType {
    fn from(value: document_transform::field_transform::TransformType) -> Self {
        use document_transform::field_transform::TransformType as V;
        match value {
            V::SetToServerValue(v) => Self::SetToServerValue(v.into()),
            V::Increment(v) => Self::Increment(Box::new(v.into())),
            V::Maximum(v) => Self::Maximum(Box::new(v.into())),
            V::Minimum(v) => Self::Minimum(Box::new(v.into())),
            V::AppendMissingElements(v) => Self::AppendMissingElements(Box::new(v.into())),
            V::RemoveAllFromArray(v) => Self::RemoveAllFromArray(Box::new(v.into())),
        }
    }
}

impl std::convert::From<crate::model::document_transform::FieldTransform> for document_transform::FieldTransform {
    fn from(value: crate::model::document_transform::FieldTransform) -> Self {
        Self {
            field_path: value.field_path.into(),
            transform_type: value.transform_type.map(|v| v.into()),
        }
    }
}

impl std::convert::From<document_transform::FieldTransform> for crate::model::document_transform::FieldTransform {
    fn from(value: document_transform::FieldTransform) -> Self {
        Self::new()
            .set_field_path(value.field_path)
            .set_transform_type(value.transform_type.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::DocumentTransform> for DocumentTransform {
    fn from(value: crate::model::DocumentTransform) -> Self {
        Self {
            document: value.document.into(),
            field_transforms: value.field_transforms.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<DocumentTransform> for crate::model::DocumentTransform {
    fn from(value: DocumentTransform) -> Self {
        Self::new()
            .set_document(value.document)
            .set_field_transforms(value.field_transforms)
    }
}

impl std::convert::From<crate::model::WriteResult> for WriteResult {
    fn from(value: crate::model::WriteResult) -> Self {
        Self {
            update_time: value.update_time.map(|v| v.into()),
            transform_results: value.transform_results.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<WriteResult> for crate::model::WriteResult {
    fn from(value: WriteResult) -> Self {
        Self::new()
            .set_update_time(value.update_time.map(|v| v.into()))
            .set_transform_results(value.transform_results)
    }
}

impl std::convert::From<crate::model::DocumentChange> for DocumentChange {
    fn from(value: crate::model::DocumentChange) -> Self {
        Self {
            document: value.document.map(|v| v.into()),
            target_ids: value.target_ids.into_iter().map(|v| v.into()).collect(),
            removed_target_ids: value.removed_target_ids.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<DocumentChange> for crate::model::DocumentChange {
    fn from(value: DocumentChange) -> Self {
        Self::new()
            .set_document(value.document.map(|v| v.into()))
            .set_target_ids(value.target_ids)
            .set_removed_target_ids(value.removed_target_ids)
    }
}

impl std::convert::From<crate::model::DocumentDelete> for DocumentDelete {
    fn from(value: crate::model::DocumentDelete) -> Self {
        Self {
            document: value.document.into(),
            read_time: value.read_time.map(|v| v.into()),
            removed_target_ids: value.removed_target_ids.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<DocumentDelete> for crate::model::DocumentDelete {
    fn from(value: DocumentDelete) -> Self {
        Self::new()
            .set_document(value.document)
            .set_removed_target_ids(value.removed_target_ids)
            .set_read_time(value.read_time.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::DocumentRemove> for DocumentRemove {
    fn from(value: crate::model::DocumentRemove) -> Self {
        Self {
            document: value.document.into(),
            read_time: value.read_time.map(|v| v.into()),
            removed_target_ids: value.removed_target_ids.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<DocumentRemove> for crate::model::DocumentRemove {
    fn from(value: DocumentRemove) -> Self {
        Self::new()
            .set_document(value.document)
            .set_removed_target_ids(value.removed_target_ids)
            .set_read_time(value.read_time.map(|v| v.into()))
    }
}

impl std::convert::From<crate::model::ExistenceFilter> for ExistenceFilter {
    fn from(value: crate::model::ExistenceFilter) -> Self {
        Self {
            target_id: value.target_id.into(),
            count: value.count.into(),
            unchanged_names: value.unchanged_names.map(|v| v.into()),
        }
    }
}

impl std::convert::From<ExistenceFilter> for crate::model::ExistenceFilter {
    fn from(value: ExistenceFilter) -> Self {
        Self::new()
            .set_target_id(value.target_id)
            .set_count(value.count)
            .set_unchanged_names(value.unchanged_names.map(|v| v.into()))
    }
}
