# Prost! and Tonic generated files

This directory contains files generated by [Prost!] and [Tonic]. This README is
needed to ensure the directory exists before invoking `protoc` and the
corresponding plugins.

[Prost!]: https://crates.io/crates/prost
[Tonic]: https://crates.io/crates/tonic
