// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LatLng {
    #[prost(double, tag="1")]
    pub latitude: f64,
    #[prost(double, tag="2")]
    pub longitude: f64,
}
// @@protoc_insertion_point(module)
