// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by sidekick. DO NOT EDIT.

impl std::convert::TryFrom<rpc::model::Code> for Code {
    type Error = crate::Error;

    fn try_from(value: rpc::model::Code) -> std::result::Result<Self, Self::Error> {
        Self::from_str_name(value.value())
            .ok_or_else(|| crate::Error::other("unknown rpc::model::Code value"))
    }
}

impl std::convert::From<Code> for rpc::model::Code {
    fn from(value: Code) -> Self {
        Self::new(value.as_str_name())
    }
}

impl std::convert::From<rpc::model::ErrorInfo> for ErrorInfo {
    fn from(value: rpc::model::ErrorInfo) -> Self {
        Self {
            reason: value.reason.into(),
            domain: value.domain.into(),
            metadata: value.metadata.into(),
        }
    }
}

impl std::convert::From<ErrorInfo> for rpc::model::ErrorInfo {
    fn from(value: ErrorInfo) -> Self {
        Self::new()
            .set_reason(value.reason)
            .set_domain(value.domain)
            .set_metadata(value.metadata)
    }
}

impl std::convert::From<rpc::model::RetryInfo> for RetryInfo {
    fn from(value: rpc::model::RetryInfo) -> Self {
        Self {
            retry_delay: value.retry_delay.map(|v| v.into()),
        }
    }
}

impl std::convert::From<RetryInfo> for rpc::model::RetryInfo {
    fn from(value: RetryInfo) -> Self {
        Self::new()
            .set_retry_delay(value.retry_delay.map(|v| v.into())
    }
}

impl std::convert::From<rpc::model::DebugInfo> for DebugInfo {
    fn from(value: rpc::model::DebugInfo) -> Self {
        Self {
            detail: value.detail.into(),
            stack_entries: value.stack_entries.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<DebugInfo> for rpc::model::DebugInfo {
    fn from(value: DebugInfo) -> Self {
        Self::new()
            .set_stack_entries(value.stack_entries)
            .set_detail(value.detail)
    }
}

impl std::convert::From<rpc::model::quota_failure::Violation> for quota_failure::Violation {
    fn from(value: rpc::model::quota_failure::Violation) -> Self {
        Self {
            subject: value.subject.into(),
            description: value.description.into(),
        }
    }
}

impl std::convert::From<quota_failure::Violation> for rpc::model::quota_failure::Violation {
    fn from(value: quota_failure::Violation) -> Self {
        Self::new()
            .set_subject(value.subject)
            .set_description(value.description)
    }
}

impl std::convert::From<rpc::model::QuotaFailure> for QuotaFailure {
    fn from(value: rpc::model::QuotaFailure) -> Self {
        Self {
            violations: value.violations.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<QuotaFailure> for rpc::model::QuotaFailure {
    fn from(value: QuotaFailure) -> Self {
        Self::new()
            .set_violations(value.violations)
    }
}

impl std::convert::From<rpc::model::precondition_failure::Violation> for precondition_failure::Violation {
    fn from(value: rpc::model::precondition_failure::Violation) -> Self {
        Self {
            r#type: value.r#type.into(),
            subject: value.subject.into(),
            description: value.description.into(),
        }
    }
}

impl std::convert::From<precondition_failure::Violation> for rpc::model::precondition_failure::Violation {
    fn from(value: precondition_failure::Violation) -> Self {
        Self::new()
            .set_type(value.r#type)
            .set_subject(value.subject)
            .set_description(value.description)
    }
}

impl std::convert::From<rpc::model::PreconditionFailure> for PreconditionFailure {
    fn from(value: rpc::model::PreconditionFailure) -> Self {
        Self {
            violations: value.violations.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<PreconditionFailure> for rpc::model::PreconditionFailure {
    fn from(value: PreconditionFailure) -> Self {
        Self::new()
            .set_violations(value.violations)
    }
}

impl std::convert::From<rpc::model::bad_request::FieldViolation> for bad_request::FieldViolation {
    fn from(value: rpc::model::bad_request::FieldViolation) -> Self {
        Self {
            field: value.field.into(),
            description: value.description.into(),
            reason: value.reason.into(),
            localized_message: value.localized_message.map(|v| v.into()),
        }
    }
}

impl std::convert::From<bad_request::FieldViolation> for rpc::model::bad_request::FieldViolation {
    fn from(value: bad_request::FieldViolation) -> Self {
        Self::new()
            .set_field(value.field)
            .set_description(value.description)
            .set_reason(value.reason)
            .set_localized_message(value.localized_message.map(|v| v.into())
    }
}

impl std::convert::From<rpc::model::BadRequest> for BadRequest {
    fn from(value: rpc::model::BadRequest) -> Self {
        Self {
            field_violations: value.field_violations.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<BadRequest> for rpc::model::BadRequest {
    fn from(value: BadRequest) -> Self {
        Self::new()
            .set_field_violations(value.field_violations)
    }
}

impl std::convert::From<rpc::model::RequestInfo> for RequestInfo {
    fn from(value: rpc::model::RequestInfo) -> Self {
        Self {
            request_id: value.request_id.into(),
            serving_data: value.serving_data.into(),
        }
    }
}

impl std::convert::From<RequestInfo> for rpc::model::RequestInfo {
    fn from(value: RequestInfo) -> Self {
        Self::new()
            .set_request_id(value.request_id)
            .set_serving_data(value.serving_data)
    }
}

impl std::convert::From<rpc::model::ResourceInfo> for ResourceInfo {
    fn from(value: rpc::model::ResourceInfo) -> Self {
        Self {
            resource_type: value.resource_type.into(),
            resource_name: value.resource_name.into(),
            owner: value.owner.into(),
            description: value.description.into(),
        }
    }
}

impl std::convert::From<ResourceInfo> for rpc::model::ResourceInfo {
    fn from(value: ResourceInfo) -> Self {
        Self::new()
            .set_resource_type(value.resource_type)
            .set_resource_name(value.resource_name)
            .set_owner(value.owner)
            .set_description(value.description)
    }
}

impl std::convert::From<rpc::model::help::Link> for help::Link {
    fn from(value: rpc::model::help::Link) -> Self {
        Self {
            description: value.description.into(),
            url: value.url.into(),
        }
    }
}

impl std::convert::From<help::Link> for rpc::model::help::Link {
    fn from(value: help::Link) -> Self {
        Self::new()
            .set_description(value.description)
            .set_url(value.url)
    }
}

impl std::convert::From<rpc::model::Help> for Help {
    fn from(value: rpc::model::Help) -> Self {
        Self {
            links: value.links.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<Help> for rpc::model::Help {
    fn from(value: Help) -> Self {
        Self::new()
            .set_links(value.links)
    }
}

impl std::convert::From<rpc::model::LocalizedMessage> for LocalizedMessage {
    fn from(value: rpc::model::LocalizedMessage) -> Self {
        Self {
            locale: value.locale.into(),
            message: value.message.into(),
        }
    }
}

impl std::convert::From<LocalizedMessage> for rpc::model::LocalizedMessage {
    fn from(value: LocalizedMessage) -> Self {
        Self::new()
            .set_locale(value.locale)
            .set_message(value.message)
    }
}

impl std::convert::From<rpc::model::HttpRequest> for HttpRequest {
    fn from(value: rpc::model::HttpRequest) -> Self {
        Self {
            method: value.method.into(),
            uri: value.uri.into(),
            body: value.body.into(),
            headers: value.headers.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<HttpRequest> for rpc::model::HttpRequest {
    fn from(value: HttpRequest) -> Self {
        Self::new()
            .set_method(value.method)
            .set_uri(value.uri)
            .set_headers(value.headers)
            .set_body(value.body)
    }
}

impl std::convert::From<rpc::model::HttpResponse> for HttpResponse {
    fn from(value: rpc::model::HttpResponse) -> Self {
        Self {
            status: value.status.into(),
            reason: value.reason.into(),
            body: value.body.into(),
            headers: value.headers.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<HttpResponse> for rpc::model::HttpResponse {
    fn from(value: HttpResponse) -> Self {
        Self::new()
            .set_status(value.status)
            .set_reason(value.reason)
            .set_headers(value.headers)
            .set_body(value.body)
    }
}

impl std::convert::From<rpc::model::HttpHeader> for HttpHeader {
    fn from(value: rpc::model::HttpHeader) -> Self {
        Self {
            key: value.key.into(),
            value: value.value.into(),
        }
    }
}

impl std::convert::From<HttpHeader> for rpc::model::HttpHeader {
    fn from(value: HttpHeader) -> Self {
        Self::new()
            .set_key(value.key)
            .set_value(value.value)
    }
}

impl std::convert::From<rpc::model::Status> for Status {
    fn from(value: rpc::model::Status) -> Self {
        Self {
            code: value.code.into(),
            message: value.message.into(),
            details: value.details.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl std::convert::From<Status> for rpc::model::Status {
    fn from(value: Status) -> Self {
        Self::new()
            .set_code(value.code)
            .set_message(value.message)
            .set_details(value.details)
    }
}
