// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rust_prost

import (
	"embed"
	"errors"
	"fmt"
	"log/slog"
	"maps"
	"os/exec"
	"path"
	"sort"
	"strings"
	"time"

	"github.com/googleapis/google-cloud-rust/generator/internal/api"
	"github.com/googleapis/google-cloud-rust/generator/internal/config"
	"github.com/googleapis/google-cloud-rust/generator/internal/language"
	"github.com/googleapis/google-cloud-rust/generator/internal/license"
	"github.com/googleapis/google-cloud-rust/generator/internal/protobuf"
	"github.com/googleapis/google-cloud-rust/generator/internal/rust"
)

type root struct {
	CopyrightYear string
	BoilerPlate   []string
	Packages      []*protobufPackage
}

type protobufPackage struct {
	Name     string
	ID       string
	Filename string
	Children []*protobufPackage
}

func Generate(model *api.API, outdir string, cfg *config.Config) error {
	if cfg.General.SpecificationFormat != "protobuf" {
		return fmt.Errorf("The `rust+prost` generator only supports `protobuf` as an specification source, outdir=%s", outdir)
	}
	if err := runExternalCommand("cargo", "--version"); err != nil {
		return fmt.Errorf("got an error trying to run `cargo --version`, the instructions on https://www.rust-lang.org/learn/get-started may solve this problem: %w", err)
	}
	if err := runExternalCommand("protoc", "--version"); err != nil {
		return fmt.Errorf("got an error trying to run `protoc --version`, the instructions on https://grpc.io/docs/protoc-installation/ may solve this problem: %w", err)
	}
	if err := runExternalCommand("protoc-gen-tonic", "--version"); err != nil {
		return fmt.Errorf("got an error trying to run `protoc-gen-tonic --version`, `cargo install protoc-gen-tonic` may solve this problem: %w", err)
	}
	if err := runExternalCommand("protoc-gen-prost", "--version"); err != nil {
		return fmt.Errorf("got an error trying to run `protoc-gen-prost --version`, `cargo install protoc-gen-prost` may solve this problem: %w", err)
	}
	// Use the Rust generator for most of the code.
	codecOptions := maps.Clone(cfg.Codec)
	codecOptions["template-override"] = "templates/prost"
	if err := rust.Generate(model, outdir, codecOptions); err != nil {
		return err
	}
	// Then use our own templates to generate the glue between Prost-generated
	// code and our generated code.
	root, err := buildRoot(model, cfg)
	if err != nil {
		return err
	}
	provider := templatesProvider()
	generatedFiles := language.WalkTemplatesDir(Templates, "templates/prost")
	if err := language.GenerateFromRoot(outdir, root, provider, generatedFiles); err != nil {
		return err
	}
	// Finally, use `protoc` to generate the Tonic and Prost! code.
	return protoc(outdir, cfg)
}

func protoc(outdir string, cfg *config.Config) error {
	files, err := protobuf.DetermineInputFiles(cfg.General.SpecificationSource, cfg.Source)
	if err != nil {
		return err
	}
	args := []string{
		"--prost_out", path.Join(outdir, "protos"),
		"--tonic_out", path.Join(outdir, "protos"),
	}
	for _, name := range config.SourceRoots(cfg.Source) {
		if path, ok := cfg.Source[name]; ok {
			args = append(args, "--proto_path")
			args = append(args, path)
		}
	}
	args = append(args, files...)
	return runExternalCommand("protoc", args...)
}

func runExternalCommand(c string, arg ...string) error {
	slog.Info("running protoc", "arg", arg)
	cmd := exec.Command(c, arg...)
	cmd.Dir = "."
	if output, err := cmd.CombinedOutput(); err != nil {
		if ee := (*exec.ExitError)(nil); errors.As(err, &ee) && len(ee.Stderr) > 0 {
			return fmt.Errorf("%v: %v\n%s", cmd, err, ee.Stderr)
		}
		return fmt.Errorf("%v: %v\n%s", cmd, err, output)
	}
	return nil
}

//go:embed all:templates
var Templates embed.FS

func templatesProvider() language.TemplateProvider {
	return func(name string) (string, error) {
		contents, err := Templates.ReadFile(name)
		if err != nil {
			return "", err
		}
		return string(contents), nil
	}
}

func buildRoot(model *api.API, cfg *config.Config) (*root, error) {
	year, _, _ := time.Now().Date()
	generationYear := fmt.Sprintf("%04d", year)
	for key, definition := range cfg.Codec {
		switch {
		case key == "copyright-year":
			generationYear = definition
		default:
			// Ignore
		}
	}
	result := &root{
		CopyrightYear: generationYear,
		BoilerPlate: append(license.LicenseHeaderBulk(),
			"",
			" Code generated by sidekick. DO NOT EDIT."),
	}
	packagesByID := map[string]*protobufPackage{}
	addEnumPackages(packagesByID, model)
	addMessagePackages(packagesByID, model)
	addServicePackages(packagesByID, model)
	for name, pkg := range packagesByID {
		sort.Slice(pkg.Children, func(i, j int) bool {
			return pkg.Children[i].Name < pkg.Children[j].Name
		})
		if strings.Contains(name, ".") {
			continue
		}
		result.Packages = append(result.Packages, pkg)
	}
	sort.Slice(result.Packages, func(i, j int) bool {
		return result.Packages[i].Name < result.Packages[j].Name
	})
	return result, nil
}

func addEnumPackages(packagesByID map[string]*protobufPackage, model *api.API) {
	for _, x := range model.State.EnumByID {
		addPackage(x.Package, packagesByID)
	}
}

func addMessagePackages(packagesByID map[string]*protobufPackage, model *api.API) {
	for _, x := range model.State.MessageByID {
		addPackage(x.Package, packagesByID)
	}

}

func addServicePackages(packagesByID map[string]*protobufPackage, model *api.API) {
	for _, x := range model.State.ServiceByID {
		addPackage(x.Package, packagesByID)
	}
}

func addPackage(pkgID string, packagesByID map[string]*protobufPackage) {
	if pkg, ok := packagesByID[pkgID]; ok {
		pkg.Filename = packageFilename(pkgID)
		return
	}
	pkg := newProtobufPackage(pkgID)
	pkg.Filename = packageFilename(pkgID)
	packagesByID[pkgID] = pkg
	addChildPackage(pkg, packagesByID)
}

func newProtobufPackage(id string) *protobufPackage {
	components := strings.Split(id, ".")
	name := id
	if len(components) > 1 {
		name = components[len(components)-1]
	}
	name = rust.EscapeKeyword(name)
	return &protobufPackage{
		Name: name,
		ID:   id,
	}
}

func packageFilename(id string) string {
	if id == "google.protobuf" {
		return ""
	}
	return fmt.Sprintf("%s.rs", id)
}

func addChildPackage(child *protobufPackage, packagesByID map[string]*protobufPackage) {
	id := child.ID
	lastDot := strings.LastIndex(id, ".")
	if lastDot == -1 {
		return
	}
	parentID := child.ID[0:lastDot]
	if parentID == "" {
		return
	}
	if parent, ok := packagesByID[parentID]; ok {
		parent.Children = append(parent.Children, child)
		return
	}
	parent := newProtobufPackage(parentID)
	packagesByID[parentID] = parent
	parent.Children = append(parent.Children, child)
	addChildPackage(parent, packagesByID)
}
